app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

// Public Website
Route::get('/', 'HomeController@index');
Route::get('/configuration/step-1', 'ConfigurationController@step_1');
Route::get('/configuration/step-2', 'ConfigurationController@step_2');
Route::get('/configuration/step-3', 'ConfigurationController@step_3');
Route::get('/configuration/result/{id}', 'ConfigurationController@result');

Route::resource('contacts', 'ContactsController', ['only' => ['index', 'store']]);
Route::resource('order', 'OrderController', ['only' => ['index', 'store']]);
Route::get('/order/thankyou', 'OrderController@thankyou');
Route::resource('subscriptions', 'SubscriptionsController', ['only' => ['store']]);
Route::get('/subscriptions/thankyou', 'SubscriptionsController@thankyou');
Route::get('/unsubscribe', 'SubscriptionsController@unsubscribe');
Route::get('/unsubscribe/{id}', 'SubscriptionsController@unsubscribe');
Route::post('/unsubscribe', ['as' => 'subscriptions.unsubscribe', 'uses' => 'SubscriptionsController@unsubscribe'] );
Route::resource('benefits', 'BenefitsController', ['only' => ['index']]);
Route::resource('products', 'ProductsController', ['only' => ['index','show']]);
Route::resource('beverages', 'BeveragesController', ['only' => ['index','show']]);
Route::resource('deliveries', 'DeliveriesController', ['only' => ['index']]);
Route::get('beverages/category/{id}', 'BeveragesController@category');
Route::get('delivery', 'InfographicsController@delivery');
Route::get('nescafe-plan', 'InfographicsController@plan');
Route::resource('search', 'SearchController', ['only' => ['index','show']]);
Route::resource('businesses', 'BusinessesController', ['only' => ['show']]);
Route::get('promotions', 'HomeController@promotions');
Route::get('promotions/{slug}', 'HomeController@promotion');

/*Route::get('/business/petrolstation', 'BusinessesController@petrolstation');
Route::get('/business/hotel', 'BusinessesController@hotel');
Route::get('/business/coffeeshop', 'BusinessesController@coffeeshop');
Route::get('/business/shop', 'BusinessesController@shop');
Route::get('/business/office', 'BusinessesController@office');*/

Route::get('/information/tos', 'InformationController@tos');
Route::get('/information/cookies', 'InformationController@cookies');
Route::get('/information/security', 'InformationController@security');
Route::get('/information/general-policy', 'InformationController@general_policy');

Route::get('/sitemap.xml', 'SitemapController@index');
Route::get('/sitemap/beverages', 'SitemapController@beverages');
Route::get('/sitemap/machines', 'SitemapController@machines');
Route::get('/sitemap/products', 'SitemapController@products');

Route::resource('machines', 'MachinesController', ['only' => ['index','show']]);
// Authentication routes
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('/export', ['as' => 'export', 'uses' => 'ExportsController@index']);
Route::post('exports/orders', ['as' => 'exports.orders', 'uses' => 'ExportsController@orders']);

// Employees Intranet
Route::group(['prefix' => 'admin_rlAPkBI5RRPqmty1pVu4', 'namespace' => 'Admin', 'middleware' => 'auth'], function() {
	// Only admin group has access to these routes.
	Route::group(['middleware' => ['auth', 'acl'], 'is' => 'administrator'], function() {
		Route::resource('users', 'UsersController', ['only' => ['index', 'create', 'destroy', 'edit', 'update', 'store']]);

		Route::get('orders/export', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.orders.export', 'uses' => 'OrdersController@export']);

		Route::post('orders/import', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.orders.import', 'uses' => 'OrdersController@import']);

		Route::get('cycles/export', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.cycles.export', 'uses' => 'CyclesController@export']);
		Route::resource('cycles', 'CyclesController', ['except' => 'index']);
		Route::post('cycles/import', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.cycles.import', 'uses' => 'CyclesController@import']);
		Route::post('verifications/import', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.verifications.import', 'uses' => 'VerificationsController@import']);
	});

	// every employee has access to these routes.
	Route::get('/', 'DashboardController@index');
	Route::resource('visits', 'VisitsController', ['only' => 'index']);
	Route::resource('own_cycles', 'OwnCyclesController', ['only' => ['edit', 'update']]);
	Route::resource('cycles', 'CyclesController');
	Route::get('cycles/disable/{id}',['as' => 'admin_rlAPkBI5RRPqmty1pVu4.cycles.disable', 'uses' => 'CyclesController@disable']);
	Route::get('users/change_password', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.users.change_password', 'uses' => 'UsersController@change_password']);
	Route::post('users/change_password', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.users.update_password', 'uses' => 'UsersController@update_password']);
	Route::resource('schedules', 'SchedulesController');
	Route::post('schedules/toggle/{id}', ['as' => 'admin_rlAPkBI5RRPqmty1pVu4.schedules.toggle', 'uses' => 'SchedulesController@toggle']);
	Route::resource('orders', 'OrdersController');
	Route::resource('objects', 'ObjectsController');
});

// Editor's Panel

app/Http/Controllers/Admin/OwnCyclesController.php
<?php namespace NescafeAlegria\Http\Controllers\Admin;

use NescafeAlegria\Http\Requests;
use NescafeAlegria\Http\Controllers\Admin\AdminController;
use NescafeAlegria\Http\Requests\ImportRequest;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;

use NescafeAlegria\Cycle;
use NescafeAlegria\Http\Requests\EmployeeEditCycleRequest;
use Illuminate\Support\Facades\Auth;

class OwnCyclesController extends AdminController {
	public function edit($id)
	{
		$cycle = Cycle::owned()->findOrFail($id);
		$userFilters = Auth::user()->getSubjectsNames();
		return view('admin.own_cycles.edit', compact('cycle', 'userFilters'));
	}

	public function update($id, EmployeeEditCycleRequest $request)
	{
		$cycle = Cycle::owned()->findOrFail($id);
		if($cycle->update($request->all()))
		{
			return redirect('admin_rlAPkBI5RRPqmty1pVu4/cycles')->with(['status' => 'success', 'message' => 'Цикълът на посещение е обновен успешно.']);
		}
	}
}

resources/views/admin/own_cycles/edit.blade.php
@extends('admin')

@section('content')
	<div class='row align-center'>
		<div class='small-12 medium-10 column'>
			<h1>Промяна на цикъл</h1>
			{!! Form::model($cycle, ['route' => ['admin_rlAPkBI5RRPqmty1pVu4.own_cycles.update', $cycle->id], 'method' => 'PUT']) !!}
				@if($cycle->bmb_number == 0)
					<div class='row'>
						<div class='small-12 medium-4 columns'>{!! Form::label('poc_name', 'Фирма') !!}</div>
						<div class='small-12 medium-8 columns'>{!! Form::text('poc_name', $cycle->poc_name) !!}</div>
					</div>
					<div class='row'>
						<div class='small-12 medium-4 columns'>{!! Form::label('address', 'Адрес') !!}</div>
						<div class='small-12 medium-8 columns'>{!! Form::text('address', $cycle->address) !!}</div>
					</div>
					<div class='row'>
						<div class='small-12 medium-4 columns'>{!! Form::label('city', 'Град') !!}</div>
						<div class='small-12 medium-8 columns'>{!! Form::text('city', $cycle->city) !!}</div>
					</div>
				@endif
				<div class='row'>
					<div class='small-12 medium-4 columns'>{!! Form::label('trading_person_name', 'ТП') !!}</div>
					<div class='small-12 medium-8 columns'>
					<select name='trading_person_name' id='trading_person_name'>
						@foreach($userFilters as $u)
							<option value='{{$u}}' {{ $cycle->trading_person_name == $u ? 'selected' : ''}}>{{$u}}</option>
						@endforeach
					</select>
					</div>
				</div>
				<div class='row'>
					<div class='small-12 medium-4 columns'>{!! Form::label('start_date', 'Дата на започнане') !!}</div>
					<div class='small-12 medium-8 columns'>{!! Form::text('start_date', $cycle->start_date , ['class'=> 'with-datepicker', 'data-from-date' => Carbon\Carbon::today()->toDateString()]) !!}</div>
				</div>
				<div class='row'>
					<div class='small-12 medium-4 columns'>{!! Form::label('period', 'Цикъл(дни)') !!}</div>
					<div class='small-12 medium-8 columns'>{!! Form::select('period', array('7' => 7, '14' => 14, '28' => 28, '168' => 168), $cycle->period) !!}</div>
				</div>
				{!! Form::submit('Запази', ['class' => 'button']) !!}
			{!! Form::close() !!}
		</div>
	</div>
@endsection

resources/views/admin/own_cycles/index.blade.php
@extends('admin')
<?php $i = 1; ?>
@section('content')
	<div class='column'>
		<h1>
			Цикли на посещения
		</h1>
		<table class='stack hover'>
			<thead>
				<tr>
					<th>#</th>
					<th>Дата</th>
					<th>Цикъл</th>
					<th>ТП</th>
					<th>Обект</th>
					<th>Кафе Машина</th>
					<th>Корекция</th>
				</tr>
			</thead>
			<tbody>
			@foreach($cycles as $cycle)
				<tr>
					<td>{{ $i }}</td>
					<td>{{ $cycle->start_date }}</td>
					<td>{{ $cycle->period }}</td>
					<td>{{ $cycle->trading_person_name }}</td>
					<td>
						{{ $cycle->poc_name }} <br>
						{{ $cycle->address }} <br>
					</td>
					<td>
						{{$cycle->bmb_number}}, {{$cycle->machine_sn}} ({{$cycle->machine_model}})
					</td>
					<td class='text-right' style='font-size: 1.2rem;'>
						<a href='{{route('admin_rlAPkBI5RRPqmty1pVu4.own_cycles.edit', $cycle)}}' style='margin-right: 10px;'><i class='fa fa-pencil-square-o' aria-hidden='true'></i></a>
					</td>
				</tr>
				<?php $i++; ?>
			@endforeach
			</tbody>
			<tfoot>
				<tr>
					<th>#</th>
					<th>Дата</th>
					<th>Цикъл</th>
					<th>ТП</th>
					<th>Обект</th>
					<th>Кафе Машина</th>
					<th>Корекция</th>
				</tr>
			</tfoot>
		</table>
		<div class='row column align-center text-center'>
			{!! $cycles->render() !!}
		</div>
	</div>
@endsection